### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by drizzt09** [rivenmedia/riven#461]
built using the docker compose and when trying to access site I get 500 internal error and see the below error in logs:
`2024-06-22 17:15:22 TypeError: fetch failed`
`2024-06-22 17:15:22 at node:internal/deps/undici/undici:12502:13`
`2024-06-22 17:15:22 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {`
`2024-06-22 17:15:22 [cause]: Error: connect ECONNREFUSED 127.0.0.1:8080`
`2024-06-22 17:15:22 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {`
`2024-06-22 17:15:22 errno: -111,`
`2024-06-22 17:15:22 code: 'ECONNREFUSED',`
`2024-06-22 17:15:22 syscall: 'connect',`
`2024-06-22 17:15:22 address: '127.0.0.1',`
`2024-06-22 17:15:22 port: 8080`
`2024-06-22 17:15:22 }`
`2024-06-22 17:15:22 }`

I seem to remember a similar issue with OSP in the past with python conflicts and workers not starting inside the container. not sure if this is same issue or similar.

**Comment by dreulavelle** [comment]
The frontend is available at 3000, not 8080

**Comment by drizzt09** [comment]
I'm not using 8080. I'm using 3000. Yet the error still persists. 
I tried adding th port to the compose config but still the same error.

**Comment by drizzt09** [comment]
> The frontend is available at 3000, not 8080

I'm not using 8080. I'm using 3000. Yet the error still persists. 
I tried adding th port to the compose config but still the same error.

**Comment by dreulavelle** [comment]
can you post the compose you're using here. You should only need the basics.

```yml
services:
  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://localhost:3000
      - TZ=America/New_York
    volumes:
      - ./data:/riven/data
      - /mnt:/mnt
    ports:
      - "3000:3000"
```

**Comment by drizzt09** [comment]
That's what I have for the compose, except localhost is hosts internal Ip
(but I have tried both ways).

Mine also has 8080:8080 configured now to seeing it got past this error but
it does not. Those are the only 2 differences.

**Comment by drizzt09** [comment]
finally back to PC
Here is what I start with:
`
services:
  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://192.168.0.15:3000
      - TZ=America/New_York
    volumes:
      - ./data:/riven/data
      - /mnt:/mnt
    ports:
      - "3000:3000"
`
then after it pulls down what it needs and builds it out and starts the container this is what the compose looks like after:
`
{
  "services": {
    "riven": {
      "container_name": "riven",
      "image": "spoked/riven:latest",
      "environment": [
        "PUID=1000",
        "PGID=1000",
        "ORIGIN=http://192.168.0.15:3000",
        "TZ=America/New_York",
        "PATH=/app/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LANG=C.UTF-8",
        "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
        "PYTHON_VERSION=3.11.9",
        "PYTHON_PIP_VERSION=24.0",
        "PYTHON_SETUPTOOLS_VERSION=65.5.1",
        "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py",
        "PYTHON_GET_PIP_SHA256=dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9",
        "PYTHONUNBUFFERED=1",
        "FORCE_COLOR=1",
        "TERM=xterm-256color",
        "VIRTUAL_ENV=/app/.venv"
      ],
      "labels": {
        "description": "Riven Media Server",
        "name": "Riven",
        "url": "https://github.com/rivenmedia/riven"
      },
      "ports": [
        "0.0.0.0:3000:3000/tcp",
        ":::3000:3000/tcp"
      ],
      "volumes": [
        {
          "Type": "bind",
          "Source": "/usr/data",
          "Target": "/riven/data"
        },
        {
          "Type": "bind",
          "Source": "/mnt",
          "Target": "/mnt"
        }
      ],
      "networks": {
        "cosmos-riven-default": {}
      },
      "routes": null,
      "restart": "unless-stopped",
      "devices": null,
      "expose": [],
      "depends_on": [],
      "tty": true,
      "entrypoint": "fish /riven/entrypoint.sh",
      "working_dir": "/riven",
      "hostname": "45fd893d0b13",
      "network_mode": "cosmos-riven-default",
      "healthcheck": {
        "test": null,
        "interval": 0,
        "timeout": 0,
        "retries": 0,
        "start_period": 0
      }
    }
  }
}
`

**Comment by dreulavelle** [comment]
hmm, is cosmos editing the compose or something?

**Comment by Pukabyte** [comment]
@dreulavelle I would recommend putting the overseerr webhook on a different port since 8080 is too common and usually used by other services if people haven’t setup networks properly and are using host

**Comment by dreulavelle** [comment]
People can just move the port in the compose

**Comment by Pukabyte** [comment]
Yea, but I think it’s his issue here where it hangs on port 8080

@drizzt09 try changing 8080:8080 to 8980:8080

**Comment by Pukabyte** [comment]
I got around it on my other server that had no docker support by changing the 8080 port in main.py

**Comment by drizzt09** [comment]
i dont even have jellyseer installed. I removed 8080 from the compose
when i try to visit http://192.168.0.15:3000/ I "still" get the above original error for 8080

**Comment by dreulavelle** [comment]
Try this @drizzt09 

```yml
services:
  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://192.168.0.15:3000
      - TZ=America/New_York
    volumes:
      - ./data:/riven/data
      - /mnt:/mnt
    ports:
      - "3000:3000"
      - "8980:8080"
      ```
