### ISSUE TITLE
riven 500 | Internal error

### ISSUE THREAD

**Issue by vuongtt92** [rivenmedia/riven#662]
hi, I'm trying to setup riven. The front end has started sucessfully,  I've gone through the initial setup but immediately after that it shows "500 | Internal error". 
By checking the log, I see that the backend is trying to restart constantly but unsuccessful, the last error in the log is 
```
24-08-22 11:37:52 | :x: ERROR     | program.validate_database - Database connection failed. Is the database running? 
24-08-22 11:46:59 |  CRITICAL  | main.<module> - Server has been stopped
```
Could anyone help? Thank you
here's my compose, could you pls. take a look to see what's wrong with it?
I'm following the savvy guide
I tried also the DMB ([](https://github.com/I-am-PUID-0/DMB)), apparently there's a same issue with the backend
```
services:
  riven-frontend:
    image: spoked/riven-frontend:latest
    container_name: riven-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    environment:
      - PUID=1027
      - PGID=100
      - ORIGIN=http://192.168.124.22:3000  # Set to IP or FQDN of the server
      - BACKEND_URL=http://192.168.124.22:8080
      - DIALECT=postgres
      - DATABASE_URL=postgres://postgres:postgres@riven-db/riven
      - TZ=Asia/Saigon
    network_mode: bridge
    depends_on:
      riven:
        condition: service_healthy

  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    ports:
      - "8080:8080"
    tty: true
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Asia/Saigon
      - RIVEN_FORCE_ENV=true
      #- RIVEN_DATABASE_HOST=postgresql+psycopg2://postgres:postgres@riven-db:5432/riven
      - RIVEN_DATABASE_HOST=postgresql+psycopg2://postgres:postgres@postgres/riven-db/riven
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    network_mode: bridge
    volumes:
      - /volume2/docker/riven/data:/riven/data
      - /volume2/media:/mnt
    depends_on:
      riven_postgres:
        condition: service_healthy

  riven_postgres:
    image: postgres:16.3-alpine3.20
    container_name: riven-db
    #ports:
      #- "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    network_mode: bridge
    volumes:
      - /volume2/docker/riven/data/riven-db:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
```
