### ISSUE TITLE
[Feature Request] Deleting torrent on Riven also deletes on RD

### ISSUE THREAD

**Issue by raphaeleduardo42** [rivenmedia/riven#789]
I'm using Infuse as my Media service, and deleting thing from Riven also requires me delete it from RD via DMM.
Another great option would be create a DAV serve with itens from Riven only.

**Comment by dreulavelle** [comment]
I never delete on RD, never had to 🤷

**Comment by raphaeleduardo42** [comment]
Thinking about you sad @dreulavelle I've found a easier way to handle it, use another tool to create the webdav server. That way Riven can directly controls what Infuse can see.

``` YAML
webdav:
    image: derkades/webdav
    ports:
      - 8888:80
    restart: unless-stopped
    volumes:
      - /mnt/library:/data
      - /mnt/zurg:/mnt/zurg:rshared
```
